language: python
branches:
  only:
  - master

install:
- git config --global user.email "rblack@austincc.edu"
- git config --global user.name "Roie Black"
- pip install -r requirements.txt

script:
- make publish
